---
Name: my-project-name-here
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/production/editor.css'
---
Only:
  environment: 'live'
---
Google: 
  analytics: 'UA-XXXXXXXXX-X'
---
Only:
  environment: 'dev'
---
Google: 
  analytics: 'analytics-disabled-for-dev-env'
---
Only:
  environment: 'test'
---
Google: 
  analytics: 'analytics-disabled-for-test-env'