---
Name: skeletor
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'resources/app/dist/editor.css'

---
Only:
  environment: 'dev'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface: 
    calls:
      LogFileHandler: [ pushHandler, [ '%$LogFileHandler' ] ]
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "./silverstripe.log"
      - "info"